### ISSUE TITLE
Nice to have: export parsed file in a machine readable format, or render markdown

### ISSUE THREAD

**Issue by vlad-ivanov-name** [Nicoretti/prysk#111]
It would be cool if prysk could assist in previewing test files with comments. For example, some of the comments may include markdown. This is kind of similar to how rust does it with their documentation

**Comment by Nicoretti** [comment]
Hi Vlad,

hope you are doing well :smiley: !

Thanks for the input ("feature request"). In the long run I plan to decouple the `cram/prysk - file format` from the execution engine, by introducing an "intermediate" (machine readable) file format.  
This will have various advantages. To name some:

* Prysk can support multiple input formats without breaking compatibility with the cram format
  (Suggestions what about the cram input format could be improved are welcome :smile: )
* The intermediate format can be used as input for new/other tools
  (E.g. a tool or sub command which will generate a preview)

I can't and won't promise anything anytime soon :cry:, but I definitely take your thought(s) into account and I'll try to come up 
with a "roadmap" when I can make some time for planning :notebook:.

best
Nico

**Comment by Nicoretti** [comment]
The current work in progress can be found [here](https://github.com/Nicoretti/prysk-reboot/tree/main/docs/design).

(shelved)
