### ISSUE TITLE
Parallelize tests

### ISSUE THREAD

**Issue by mehulkar** [Nicoretti/prysk#165]
It would be nice to run multiple tests at the same time to make them faster. I'm not sure, but it seems `TESTDIR` is unique for tests, so there is some isolation built in already that would prevent tests from running into each other.

**Comment by Nicoretti** [comment]
Hi @mehulkar,

I think this is a solved issue see https://github.com/Nicoretti/prysk/discussions/128#discussioncomment-4950209.

best
Nico

**Comment by Nicoretti** [comment]
@mehulkar quick follow up in case the setup is unclear.

1. Install `prysk` with `pytest-plugin`
```shell
pip install "prysk[pytest-plugin]"
``` 

2. Install `pytest-xdist` for parallel test execution 
```shell
pip install pytest-xdist
```

3. Execute your `prysk` tests using `pytest` in parallel
```shell
pytest -n auto /Path/To/Your/Test/Folder
```
