### ISSUE TITLE
Prysk 0.13 Causes Test Failures in Unrelated pytest Tests

### ISSUE THREAD

**Issue by sanssecours** [Nicoretti/prysk#169]
# Description

The latest version of Prysk seems to cause test failures in unrelated tests executed by pytest under certain circumstances. For example, in the repository [`mytoolit/icoc`](https://github.com/mytoolit/ICOc/) the CI tests [fail with Prysk `0.13.0`](https://github.com/MyTooliT/ICOc/commit/28b0481fe8027f46cb3b4de4732ec99430157914) but [finish successfully with Prysk `0.12.2`](https://github.com/MyTooliT/ICOc/commit/0d01ba1d4e0ec0c82a07195b53fba2205b3c5cc6).

# Steps to Reproduce

Execute the commands below (on Linux, macOS or Windows):

```sh
pip install prysk==0.13
git clone https://github.com/MyTooliT/ICOc.git
cd ICOc
git reset --hard '28b0481fe8027f46cb3b4de4732ec99430157914'
pip install -e .[dev,test]
pytest --ignore-glob='*network.py' --ignore-glob='*commander.py'
```

# Expected Result

All tests finish sucessfully.

# Actual Result

The test `mytoolit/utility/environment.py::mytoolit.utility.environment.add_commander_path_to_environment` fails:

```
012 Add path to Simplicity Commander (`commander`) to `PATH`
013
014     Example
015     -------
016
017     >>> from os import environ
018     >>> length_path_before = len(environ['PATH'])
019     >>> add_commander_path_to_environment()
020     >>> length_path_after = len(environ['PATH'])
021     >>> length_path_after > length_path_before
Expected:
    True
Got:
    False
```

# Additional Information

The failed test just checks if the `PATH` **environment variable** was extended by the method `add_commander_path_to_environment`. Running only a **subset of the test** with

```sh
pytest mytoolit/utility
```

**works without problems**, even with Prysk 0.13.0. The **latest version Prysk** (`master` branch):

```sh
pip install git+https://github.com/Nicoretti/prysk.git
```

**does not fix the issue** (yet). After I install Prysk 0.12:

```sh
pip install prysk==0.12.2
```

the command

```sh
pytest --ignore-glob='*network.py' --ignore-glob='*commander.py'
```

works without any problems.

## System Information

**Operating Systems:**
- Linux (Ubuntu)
- macOS
- Windows

**Python Versions:**
- CPython 3.8  
- CPython 3.9
- CPython 3.10
- CPython 3.11

**Prysk Version**: `0.13+`

**Comment by Nicoretti** [comment]
Hi @sanssecours,

thanks for reporting 👍, I'll try to have a closer look at it at the weekend.

Can you in parallel check if your test(s) is also failing if you disable the prysk plugin (`-p no:prysk`)? 
```shell
pytest -p no:prysk --ignore-glob='*network.py' --ignore-glob='*commander.py' 
```

best
Nico

**Comment by sanssecours** [comment]
> Hi @sanssecours,
> 
> thanks for reporting 👍, I'll try to have a closer look at it at the weekend.

Thank you 💖.

> Can you in parallel check if your test(s) is also failing if you disable the prysk plugin (`-p no:prysk`)?
> 
> ```shell
> pytest -p no:prysk --ignore-glob='*network.py' --ignore-glob='*commander.py' 
> ```

The command above reported not test failure 👍.

**Comment by Nicoretti** [comment]
Hi @sanssecours,

Yesterday I was doing some debugging and I have identified the issue. Even though the fix/problem is "trivial" it is high impact (imho), so thanks once more for reporting!

I'll provide a PR and Release to address the issue the next couple of days.

BTW nice product/project you have, like it 👍.

best
Nico
