### ISSUE TITLE
Feature to get dropped into a shell at a specific point of a prysk test

### ISSUE THREAD

**Issue by LMG** [Nicoretti/prysk#79]
This would allow one to observe the state and debug a test more easily

**Comment by Nicoretti** [comment]
@LMG so if I got you correctly you would want to have a flag like the existing `-i` `--interactive`, but instead of asking for confirmation you would wan't to be given a shell within the current `Test`/`Test-Environment`?

**Comment by Nicoretti** [comment]
(shelved)
