### ISSUE TITLE
Warn if a test file contains only comments

### ISSUE THREAD

**Issue by LMG** [Nicoretti/prysk#84]
Right now prysk doesn't warn if a file only contains comments. 
We had a file were by mistake the spaces were not added before the tests commands.

This looks barely different from a normal test and is very confusing to debug. It would be nice if prysk warned us.

**Comment by Nicoretti** [comment]
@LMG good point, sounds like a helpful improvement to me.

**Comment by Nicoretti** [comment]
(shelved)
